# Generated by Django 3.2.13 on 2022-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nat_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
