# Generated by Django 3.2.5 on 2022-09-23 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=35)),
                ('county', models.CharField(max_length=35)),
                ('number_of_units', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=35)),
                ('units', models.PositiveIntegerField()),
                ('property_image', models.ImageField(null=b'I01\n', upload_to='property')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
