# Generated by Django 4.1.7 on 2023-03-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_feet', models.FloatField()),
                ('price_per_squre_foot', models.PositiveIntegerField()),
                ('Type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=35)),
                ('county', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('zipcode', models.PositiveBigIntegerField()),
                ('property_type', models.CharField(choices=[('C', 'commercial'), ('R', 'Residential')], max_length=5)),
                ('property_image', models.ImageField(null=b'I01\n', upload_to='propetry')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentailProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=35)),
                ('market_rent', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('square_feet', models.FloatField()),
                ('number_of_units', models.PositiveIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
