# Generated by Django 3.2.13 on 2022-09-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220921_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentailproperty',
            old_name='property_name',
            new_name='property',
        ),
    ]
